export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const EMPTY_CART = "EMPTY_CART";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
export const NEW_SHIPPING_SUCCESS = "NEW_SHIPPING_SUCCESS";
export const NEW_SHIPPING_FAILED = "NEW_SHIPPING_FAILED";

export const UPDATE_SHIPPING_INFO = "UPDATE_SHIPPING_INFO";
export const UPDATE_SHIPPING_SUCCESS = "UPDATE_SHIPPING_SUCCESS";
export const UPDATE_SHIPPING_FAILED = "UPDATE_SHIPPING_FAILED";

export const ADDRESS_DETAILS_REQUEST = "ADDRESS_DETAILS_REQUEST";
export const ADDRESS_DETAILS_SUCCESS = "ADDRESS_DETAILS_SUCCESS";
export const ADDRESS_DETAILS_FAILED = "ADDRESS_DETAILS_FAILED";